force-app/main/default/objects/Historico_de_pesquisa__c/Historico_de_pesquisa__c.object-meta.xml
<CustomObject>
    <label>Histórico de pesquisa</label>
    <nameField>
        <displayFormat>HTS-{0000}</displayFormat>
        <label>Histórico de pesquisa</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Históricos de pesquisas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Historico_de_pesquisa__c/fields/Bairro__c.field-meta.xml
<CustomField>
    <fullName>Bairro__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Bairro</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_de_pesquisa__c/fields/Cidade__c.field-meta.xml
<CustomField>
    <fullName>Cidade__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Cidade</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_de_pesquisa__c/fields/Estado__c.field-meta.xml
<CustomField>
    <fullName>Estado__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Estado</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Historico_de_pesquisa__c/fields/Logradouro__c.field-meta.xml
<CustomField>
    <fullName>Logradouro__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Logradouro</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ViaCepController.cls
public with sharing class ViaCepController {
    @AuraEnabled(cacheable=true)
    public static Map<String, Object> getEnderecoPorCep(String cep) {
        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint('https://viacep.com.br/ws/' + cep + '/json/');
        request.setMethod('GET');
        HttpResponse response = http.send(request);
        if (response.getStatusCode() == 200) {
            Map<String, Object> address = (Map<String, Object>) JSON.deserializeUntyped(response.getBody());
            if (!address.containsKey('erro')) {
                return address;
            }
        }
        return null;
    }

    @AuraEnabled
    public static void salvaHistoricoDePesquisa(String logradouro, String bairro, String cidade, String estado) {
        Historico_de_pesquisa__c historico = new Historico_de_pesquisa__c(
            Logradouro__c = logradouro,
            Bairro__c = bairro,
            Cidade__c = cidade,
            Estado__c = estado
        );
        insert historico;
    }
}